// see http://qiita.com/hyge_interface/items/94fbd5def8ed6be3afea#but_1
var Gestures = [

  { key: "Angry（怒る）",
    list: ["Angry_1",
           "Angry_2",
           "Angry_3"] },

  { key: "BowShort（短い礼）",
    list: ["BowShort_1",
           "BowShort_2",
           "BowShort_3"] },

  { key: "But（でも）",
    list: ["But_1"] },

  { key: "CalmDown（静める）",
    list: ["CalmDown_1",
           "CalmDown_2",
           "CalmDown_3",
           "CalmDown_4",
           "CalmDown_5",
           "CalmDown_6"] },

  { key: "Choice（選ぶ）",
    list: ["Choice_1"] },

  { key: "ComeOn（呼び寄せる）",
    list: ["ComeOn_1"] },

  { key: "Confused（困る）",
    list: ["Confused_1",
           "Confused_2"] },

  { key: "CountFive（５つ数える）",
    list: ["CountFive_1"] },

  { key: "CountFour（４つ数える）",
    list: ["CountFour_1"] },

  { key: "CountMore（数を数える）",
    list: ["CountMore_1"] },

  { key: "CountOne（１つ数える）",
    list: ["CountOne_1"] },

  { key: "CountThree（３つ数える）",
    list: ["CountThree_1"] },

  { key: "CountTwo（２つ数える）",
    list: ["CountTwo_1"] },

  { key: "Desperate（呆れる）",
    list: ["Desperate_1",
           "Desperate_2",
           "Desperate_3",
           "Desperate_4",
           "Desperate_5"] },

  { key: "DontUnderstand（理解に苦しむ）",
    list: ["DontUnderstand_1"] },


  { key: "Everything（全体に）",
    list: ["Everything_1",
           "Everything_2",
           "Everything_3",
           "Everything_4",
           "Everything_6"] },

  { key: "Excited（興奮する）",
    list: ["Excited_1"] },

  { key: "Explain（説明する）",
    list: ["Explain_1",
           "Explain_2",
           "Explain_3",
           "Explain_4",
           "Explain_5",
           "Explain_6",
           "Explain_7",
           "Explain_8",
           "Explain_10",
           "Explain_11"] },

  { key: "Far（遠くを示す）",
    list: ["Far_1",
           "Far_2",
           "Far_3"] },

  { key: "Follow（なぐさめる）",
    list: ["Follow_1"] },

  { key: "Give（あげる）",
    list: ["Give_1",
           "Give_2",
           "Give_3",
           "Give_4",
           "Give_5",
           "Give_6"] },

  { key: "Great（ガッツポーズ）",
    list: ["Great_1"] },

  { key: "HeSays（話を振る）",
    list: ["HeSays_1",
           "HeSays_2",
           "HeSays_3"] },

  { key: "Hey（呼ぶ）",
    list: ["Hey_1",
           "Hey_10",
           "Hey_2",
           "Hey_3",
           "Hey_4",
           "Hey_6",
           "Hey_7",
           "Hey_8",
           "Hey_9"] },

  { key: "Hide（隠す）",
    list: ["Hide_1"] },

  { key: "Hot（暑がる）",
    list: ["Hot_1",
           "Hot_2"] },

  { key: "IDontKnow（知らない）",
    list: ["IDontKnow_1",
           "IDontKnow_2",
           "IDontKnow_3",
           "IDontKnow_4",
           "IDontKnow_5",
           "IDontKnow_6"] },

  { key: "Joy（喜ぶ）",
    list: ["Joy_1"] },

  { key: "Kisses（投げキッス）",
    list: ["Kisses_1"] },

  { key: "Look（見まわす）",
    list: ["Look_1",
           "Look_2"] },

  { key: "Maybe（示唆）",
    list: ["Maybe_1"] },

  { key: "Me（自己を示す）",
    list: ["Me_1",
           "Me_2",
           "Me_4",
           "Me_7",
           "Me_8"] },

  { key: "Mime（身振り）",
    list: ["Mime_1",
           "Mime_2"] },

  { key: "Next（次）",
    list: ["Next_1"] },

  { key: "No（否定）",
    list: ["No_1",
           "No_2",
           "No_3",
           "No_4",
           "No_5",
           "No_6",
           "No_7",
           "No_8",
           "No_9"] },

  { key: "Nothing（全然）",
    list: ["Nothing_1",
           "Nothing_2"] },

  { key: "OnTheEvening",
    list: ["OnTheEvening_1",
           "OnTheEvening_2",
           "OnTheEvening_3",
           "OnTheEvening_4",
           "OnTheEvening_5"] },

  { key: "Please（求める）",
    list: ["Please_1",
           "Please_2",
           "Please_3"] },

  { key: "Reject（払いのける）",
    list: ["Reject_1",
           "Reject_2",
           "Reject_3",
           "Reject_4",
           "Reject_5",
           "Reject_6"] },

  { key: "Salute（お辞儀）",
    list: ["Salute_1",
           "Salute_2",
           "Salute_3"] },

  { key: "ShowFloor（下方を示す）",
    list: ["ShowFloor_1",
           "ShowFloor_2",
           "ShowFloor_3",
           "ShowFloor_4",
           "ShowFloor_5"] },

  { key: "ShowSky（上方を示す）",
    list: ["ShowSky_1",
           "ShowSky_10",
           "ShowSky_11",
           "ShowSky_12",
           "ShowSky_2",
           "ShowSky_3",
           "ShowSky_4",
           "ShowSky_5",
           "ShowSky_6",
           "ShowSky_7",
           "ShowSky_8",
           "ShowSky_9"] },

  { key: "ShowTablet（タブレットを示す）",
    list: ["ShowTablet_1",
           "ShowTablet_2",
           "ShowTablet_3"] },

  { key: "Shy（恥ずかしがる）",
    list: ["Shy_1"] },

  { key: "Stretch（伸びをする）",
    list: ["Stretch_1",
           "Stretch_2"] },

  { key: "Surprised（びっくりする）",
    list: ["Surprised_1"] },


  { key: "TakePlace（始める）",
    list: ["TakePlace_1",
           "TakePlace_2"] },

  { key: "Take（もらう）",
    list: ["Take_1"] },

  { key: "Thinking（考える）",
    list: ["Thinking_1",
           "Thinking_2",
           "Thinking_3",
           "Thinking_4",
           "Thinking_5",
           "Thinking_6",
           "Thinking_7",
           "Thinking_8"] },

  { key: "This（近くのものを示す）",
    list: ["This_1",
           "This_2",
           "This_3",
           "This_4",
           "This_5",
           "This_6",
           "This_7",
           "This_8",
           "This_9",
           "This_10",
           "This_11",
           "This_12",
           "This_13",
           "This_14",
           "This_15"] },

  { key: "WhatSThis（近くのものを尋ねる）",
    list: ["WhatSThis_1",
           "WhatSThis_2",
           "WhatSThis_3",
           "WhatSThis_4",
           "WhatSThis_5",
           "WhatSThis_6",
           "WhatSThis_7",
           "WhatSThis_8",
           "WhatSThis_9",
           "WhatSThis_10",
           "WhatSThis_11",
           "WhatSThis_12",
           "WhatSThis_13",
           "WhatSThis_14",
           "WhatSThis_15",
           "WhatSThis_16"] },

  { key: "Whisper（ささやく）",
    list: ["Whisper_1"] },

  { key: "Wings（飛ぶ）",
    list: ["Wings_1",
           "Wings_2",
           "Wings_3",
           "Wings_4",
           "Wings_5"] },

  { key: "Yes（同意）",
    list: ["Yes_1",
           "Yes_2",
           "Yes_3"] },

  { key: "YouKnowWhat（あのね）",
    list: ["YouKnowWhat_1",
           "YouKnowWhat_2",
           "YouKnowWhat_3",
           "YouKnowWhat_4",
           "YouKnowWhat_5",
           "YouKnowWhat_6"] },

  { key: "You（声をかける）",
    list: ["You_1",
           "You_2",
           "You_3",
           "You_4",
           "You_5"] },

  { key: "Yum（おなかいっぱい）",
    list: ["Yum_1"] }
]
